### ISSUE TITLE
Complete Open Source Checklist

### ISSUE THREAD

**Issue by gautamarora** [CondeNast/xml-to-react#23]
This is a master issue to work through the Condé Nast Open Source Checklist.

### Documentation
- [x] README
- [x] CONTRIBUTING (#24)
- [x] CODE_OF_CONDUCT
- [x] LICENSE
- [x] ISSUE_TEMPLATE
- [x] PULL_REQUEST_TEMPLATE
- [x] CHANGELOG (#25)
- [ ] Announcement Blog Post

### Development
- [x] Tests
- [x] Linter
- [x] Travis
- [ ] Examples
- [x] Clear Github History

### README Checklist
- [x] Title
- [ ] Badges 
- [x] Description
- [x] Prerequisite for using software ( if any ) (https://github.com/CondeNast/xml-to-react/pull/33)
- [x] Install
- [x] Example Usage
- [ ] Screenshots and GIFs
- [x] Contributors (https://github.com/CondeNast/xml-to-react/pull/36)
- [x] Conde Nast Technology Logo (https://github.com/CondeNast/xml-to-react/pull/31)
- [x] Attributions ( mention 3rd party libs used etc. ) (https://github.com/CondeNast/xml-to-react/pull/32)
- [ ] Benchmarks (if any)
- [x] Prior Art (if any) (https://github.com/CondeNast/xml-to-react/pull/35)

### Badges Checklist:
- [x] License Badge
- [ ] Testing Badge
- [x] CI Badge
